# Java Maven CircleCI 2.0 configuration file (Check https://circleci.com/docs/2.0/language-java/ for more details)

version: 2 # circle-ci 版本

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch # 容器
    working_directory: ~/workspace/springboot2-samples # 工作目录
    steps:
      - checkout # 检查代码到工作目录
      - restore_cache:
          keys:
            - springboot2-samples-dependencies-{{ checksum "pom.xml" }} # 重新缓存依赖(如果pom.xml文件更改过)
            - springboot2-samples-dependencies- # 否则使用上次缓存的依赖
      - save_cache:
          paths:
            - ~/.m2 # 依赖存储路径
          key: springboot2-samples-dependencies-{{ checksum "pom.xml" }} # 缓存的Key
      - run: mvn clean dependency:go-offline -Dmaven.test.skip=false -Dmaven.test.failure.ignore=true -Dmaven.javadoc.skip=true -e package # 构建项目
      - run: bash <(curl -s https://codecov.io/bash) -t 82633789-5676-48f3-8373-79981064509c # codecov

workflows:
  version: 2
  workflow:
    jobs:
      - build