spring:
  datasource:
    db1:
      jdbc-url: jdbc:mysql://127.0.0.1/db1?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    db2:
      jdbc-url: jdbc:mysql://127.0.0.1/db2?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    # 连接池配置
    hikari:
      auto-commit: true          # 自动提交
      connection-timeout: 30000  # 连接超时
      idle-timeout: 600000       # 连接在池中闲置的最长时间
      max-lifetime: 1800000      # 连接在池中最长的生命周期
      minimum-idle: 30           # 池中维护的最小空闲连接数
      maximum-pool-size: 30      # 池中维护的最大连接数

mybatis:
  # mybatis 配置文件
  config-location: classpath:mybatis-config.xml